src/main/java/com/zerobase/hoops/entity/ApplyGameEntity.java
src/main/java/com/zerobase/hoops/entity/GameEntity.java
src/main/java/com/zerobase/hoops/entity/MemberGroupEntity.java
src/main/java/com/zerobase/hoops/entity/UserEntity.java
src/main/java/com/zerobase/hoops/users/config/RedisConfig.java
src/main/java/com/zerobase/hoops/users/config/SwaggerConfig.java
src/main/java/com/zerobase/hoops/users/config/WebSecurityConfig.java
src/main/java/com/zerobase/hoops/users/controller/UserController.java
src/main/java/com/zerobase/hoops/users/dto/SignUpDto.java
src/main/java/com/zerobase/hoops/users/dto/UserDto.java
src/main/java/com/zerobase/hoops/users/exception/CustomException.java
src/main/java/com/zerobase/hoops/users/exception/CustomExceptionHandler.java
src/main/java/com/zerobase/hoops/users/exception/ErrorCode.java
src/main/java/com/zerobase/hoops/users/exception/ErrorResponse.java
src/main/java/com/zerobase/hoops/users/provider/CertificationProvider.java
src/main/java/com/zerobase/hoops/users/provider/EmailProvider.java
src/main/java/com/zerobase/hoops/users/repository/EmailRepository.java
src/main/java/com/zerobase/hoops/users/repository/UserRepository.java
src/main/java/com/zerobase/hoops/users/service/UserService.java
src/main/java/com/zerobase/hoops/users/type/AbilityType.java
src/main/java/com/zerobase/hoops/users/type/GenderType.java
src/main/java/com/zerobase/hoops/users/type/PlayStyleType.java
src/test/java/com/zerobase/hoops/users/service/UserServiceTest.java

**TO-BE**
- 회원 가입 기능 구현
- 아이디, 이메일, 닉네임 중복 검사
- 비밀번호 확인
- 이메일 형식 검사
- ex. hoops@hoops.com → PASS / hoopsahoops.com → FAIL
- 비밀번호 형식 검사
- 최소 영어 대소문자 1개 이상, 숫자, 특수문자 포함 8자리~13자리
- 가입 완료 시 가입한 이메일로 인증 메일 발송 : 유효 기간 3분
- 인증 번호 생성하여 email, 인증 번호 reids 에 저장
- 비활성화 계정으로 DB 적재 (emailAuth → False)
- 인증 이메일 클릭 시 계정 활성화 (emailAuth → True)
- redis 에 저장된 키, 값 확인 후 인증 완료되면 redis 에서 삭제

Feature/hyunjae kwon #1

---

src/main/java/com/zerobase/hoops/config/SwaggerConfig.java
src/main/java/com/zerobase/hoops/users/oauth2/controller/OAuth2Controller.java
src/main/java/com/zerobase/hoops/users/oauth2/service/OAuth2Service.java
src/main/resources/application.yml

**TO-BE**
- 로그아웃 시 세션 정보 (카카오 토큰) 삭제
- 카카오 토큰 만료
- access token log out list 추가
- refresh token 삭제

feat : 카카오 로그아웃 API

---

src/main/java/com/zerobase/hoops/exception/ErrorCode.java
src/main/java/com/zerobase/hoops/gameUsers/controller/GameUserController.java
src/main/java/com/zerobase/hoops/gameUsers/dto/GameSearchResponse.java
src/main/java/com/zerobase/hoops/gameUsers/repository/GameCheckOutRepository.java
src/main/java/com/zerobase/hoops/gameUsers/service/GameUserService.java
src/main/resources/data.sql
src/test/java/com/zerobase/hoops/gameUsers/controller/GameUserControllerTest.java
src/test/java/com/zerobase/hoops/gameUsers/service/GameUserServiceTest.java

**AS-IS**
- 경기 참여 목록 조회
- 지난 경기 리스트
- 현재 참여하고 있는 경기 리스트
**TO-BE**
- 지난 경기 -> ACCEPT 된 경기 + 오늘 시점으로부터 지난 날짜로 조회
- 참여하고 있는 경기 -> ACCEPT 된 경기 + 오늘 날짜 기준 아직 시작되지 않은 경기
- 페이지네이션 적용
- [o] 테스트 코드
- [o] API 테스트

[기능 추가] 경기 참여 목록 조회

---

src/main/java/com/zerobase/hoops/entity/UserEntity.java
src/main/java/com/zerobase/hoops/security/TokenProvider.java
src/main/java/com/zerobase/hoops/users/controller/UserController.java
src/main/java/com/zerobase/hoops/users/provider/EmailProvider.java
src/main/java/com/zerobase/hoops/users/service/UserService.java
src/test/java/com/zerobase/hoops/users/service/UserServiceTest.java

**TO-BE**
- 아이디 찾기
- 가입 email로 요청 시 id 반환
- 비밀번호 찾기
- id로 요청 시 임시 비밀번호를 가져온 뒤 암호화해서 비밀번호 변경
- 변경된 비밀번호를 가입 email 로 전송

feat : 아이디/비밀번호 찾기

---

src/main/java/com/zerobase/hoops/gameUsers/controller/GameUserController.java
src/main/java/com/zerobase/hoops/gameUsers/service/GameSpecifications.java
src/main/java/com/zerobase/hoops/gameUsers/service/GameUserService.java

**AS-IS**
- 날짜 입력이 없을 경우 -> 기본 디폴트 값 : 오늘 날짜
**TO-BE**
- 날짜 입력 필수로 변경 
- 형식 ->  key : localDate / value : 2024-05-11
- page, size -> 디폴트 1로 기본설정 
- [o] 테스트 코드
- [o] API 테스트

[리펙토링] 필터링 게임조회 -> 날짜 입력 필수로 변경

---

src/main/java/com/zerobase/hoops/entity/ReportEntity.java
src/main/java/com/zerobase/hoops/exception/ErrorCode.java
src/main/java/com/zerobase/hoops/reports/controller/ReportController.java
src/main/java/com/zerobase/hoops/reports/dto/ReportDto.java
src/main/java/com/zerobase/hoops/reports/repository/ReportRepository.java
src/main/java/com/zerobase/hoops/reports/service/ReportService.java
src/test/java/com/zerobase/hoops/reports/controller/ReportControllerTest.java
src/test/java/com/zerobase/hoops/reports/service/ReportServiceTest.java

**AS-IS**
중복신고 불가능 -> 예외처리
**TO-BE**
- Report 엔티티 정규화
- 중복 신고 방지
- 유저간 신고는 한 번만 가능 -> 고의성 신고 방지
- 신고는 한 번만 가능하지만 매너점수는 매 경기마다 평가 가능함 -> 악성 및 비매너 유저 사전 강퇴
- [O] 테스트 코드
- [O] API 테스트

[리펙토링] 신고하기 기능-> 중복 신고 예외처리 추가 및 엔티티 변경

---

src/main/java/com/zerobase/hoops/entity/UserEntity.java
src/main/java/com/zerobase/hoops/gameUsers/service/GameUserService.java

public void saveMannerPoint(int point)
메소드를 이용해 평가 받은 유저의 점수의 평균 값을 자동 계산
**AS-IS**
단순히 매너 점수 저장기능 -> 평균 값을 구할 시 MannerPointEntity에서 따로 쿼리문으로 작성해서 값을 불러서 계산
**TO-BE**
매너 점수를 저장할 시 UserEntity에 평균 값을 관리

[리펙토링] 매너점수 -> UserEntity에 자동계산

---

src/main/java/com/zerobase/hoops/entity/UserEntity.java
src/main/resources/data.sql

**AS-IS**
UserEntity 에서 에러
- double 및 int 값 미설정으로 인한 에러
**TO-BE**
@Builder.Default
@Column(name = "total_ratings")
private int totalRatings = 0;
@Builder.Default
@Column(name = "total_ratings_count")
private int totalRatingsCount = 0;
@Builder.Default
@Column(name = "double_average_rating")
private double doubleAverageRating = 0.0;

[리펙토링] 매너점수 -> UserEntity 필드 값 디폴트 설정

---

src/main/java/com/zerobase/hoops/entity/UserEntity.java
src/main/java/com/zerobase/hoops/reports/controller/ReportController.java
src/main/java/com/zerobase/hoops/reports/dto/ReportListResponse.java
src/main/java/com/zerobase/hoops/reports/dto/ReportListResponseDto.java
src/main/java/com/zerobase/hoops/reports/repository/ReportRepository.java
src/main/java/com/zerobase/hoops/reports/service/ReportService.java
src/main/resources/data.sql
src/test/java/com/zerobase/hoops/reports/controller/ReportControllerTest.java
src/test/java/com/zerobase/hoops/reports/service/ReportServiceTest.java

**AS-IS**
- 유저 신고 목록 조회하기 기능 추가
**TO-BE**
- 페이징 처리
- 리턴 값
Long userId;
String userName;
String mannerPoint;
GenderType gender;
AbilityType abilityType;
PlayStyleType playStyleType;
- [o] 테스트 코드
- [o] API 테스트

[기능 추가] 유저 신고 목록 조회하기

---

src/main/java/com/zerobase/hoops/friends/repository/FriendCustomRepository.java
src/main/java/com/zerobase/hoops/friends/repository/FriendRepository.java
src/main/java/com/zerobase/hoops/gameCreator/repository/GameRepository.java
src/main/java/com/zerobase/hoops/gameCreator/repository/ParticipantGameRepository.java
src/main/java/com/zerobase/hoops/invite/repository/InviteRepository.java
src/main/java/com/zerobase/hoops/users/controller/AuthController.java
src/main/java/com/zerobase/hoops/users/oauth2/service/OAuth2Service.java
src/main/java/com/zerobase/hoops/users/service/AuthService.java
src/main/resources/data.sql
src/test/java/com/zerobase/hoops/users/service/AuthServiceTest.java

**TO-BE**
- 회원 탈퇴 기능 추가
- 회원 탈퇴 시 회원이 생성한 경기 삭제 일자 업데이트
- 회원이 생성한 경기에 참가되어 있는 회원들의 참가 상태 삭제로 변경, 삭제 일자 업데이트
- 회원이 생성한 경기에서 발생한 미응답 초대 상태 삭제로 변경, 삭제 일자 업데이트
- 내가 참가한 경기 상태 탈퇴, 탈퇴 일자 업데이트
- 내가 초대한 내역 삭제, 삭제 일자 업데이트
- 친구 요청 및 친구 목록 상태 삭제, 삭제 일자 업데이트

Feature/hyunjae kwon#48

---

src/main/java/com/zerobase/hoops/friends/controller/FriendController.java
src/main/java/com/zerobase/hoops/friends/dto/FriendDto.java
src/main/java/com/zerobase/hoops/friends/repository/FriendCustomRepository.java
src/main/java/com/zerobase/hoops/friends/repository/FriendRepository.java
src/main/java/com/zerobase/hoops/friends/repository/impl/FriendCustomRepositoryImpl.java
src/main/java/com/zerobase/hoops/friends/service/FriendService.java
src/main/java/com/zerobase/hoops/invite/controller/InviteController.java
src/test/java/com/zerobase/hoops/friends/service/FriendServiceTest.java

**TO-BE**
- 친구
- 내가 요청 받은 친구 리스트 조회
- 테스트 코드 구현
- [V] 테스트 코드
- [V] API 테스트

내가 요청 받은 친구 리스트 조회

---

src/main/java/com/zerobase/hoops/alarm/controller/NotificationController.java
src/main/java/com/zerobase/hoops/alarm/domain/NotificationDto.java
src/main/java/com/zerobase/hoops/alarm/domain/NotificationEntity.java
src/main/java/com/zerobase/hoops/alarm/repository/EmitterRepository.java
src/main/java/com/zerobase/hoops/alarm/repository/NotificationRepository.java
src/main/java/com/zerobase/hoops/alarm/service/NotificationService.java
src/main/java/com/zerobase/hoops/entity/NotificationEntity.java
src/main/java/com/zerobase/hoops/friends/service/FriendService.java
src/main/java/com/zerobase/hoops/gameCreator/service/ParticipantGameService.java

**TO-BE**
- 알림 기능을 위한 entity, dto 생성
- repository 생성
- controller 생성
- SSE 세션 연결을 위한 컨트롤러
- 로그인 한 유저의 모든 알림을 조회하는 컨트롤러
- service 생성
- SSE 세션 연결하는 서비스
- 알림 객체(Notification) 생성하는 메서드
- 사용자에게 알림을 전송하는 메서드
- 알림 전송 기능 코드에 적용
- 경기 개설자가 참가자 수락/거절 시 참가자에게 결과 알림
- 경기에서 강퇴되었을 때 사용자에게 알림
- 친구신청이 도착했을 때
**추가적으로 구현해야 하는 부분**
- 신고가 접수되었을 때 관리자에게 알림가는 기능

Feature/leejaeeun #30

---

src/main/java/com/zerobase/hoops/manager/service/ManagerService.java
src/test/java/com/zerobase/hoops/manager/service/ManagerServiceTest.java
src/test/java/com/zerobase/hoops/reports/service/ReportServiceTest.java

**AS-IS**
**TO-BE**
블랙리스트 실패 케이스 테스트 코드 추가
- [o] 테스트 코드
- [o] API 테스트

[테스트 코드 추가] 블랙리스트 실패케이스

---

src/main/java/com/zerobase/hoops/exception/ErrorCode.java
src/main/java/com/zerobase/hoops/invite/service/InviteService.java

**TO-BE**
- 경기 초대 요청
- 해당 경기가 초대 가능일때만 초대 가능하게 변경
- [V] API 테스트

refactor : 경기 초대 요청 조건 추가

---

src/main/java/com/zerobase/hoops/config/WebSecurityConfig.java
src/main/java/com/zerobase/hoops/exception/ErrorCode.java
src/main/java/com/zerobase/hoops/security/JwtAuthenticationFilter.java
src/main/java/com/zerobase/hoops/security/JwtExceptionFilter.java
src/main/java/com/zerobase/hoops/security/TokenProvider.java
src/test/java/com/zerobase/hoops/HoopsApplicationTests.java

**AS-IS**
- Jwt token filter 사용 
**TO-BE**
- 잘못된 토큰으로 요청 시 DispatcherServlet 까지 도달하지 못하고 예외 발생
- 코드 정리
- 토큰 만료, 토큰 형식, 로그 아웃, 블랙리스트 검증 및 예외 처리
- JwtExceptionFilter 추가
- WebSecurityConfig 에서 기존 필터 앞에서 예외 필터 실행하도록 추가

feat : JwtExceptionFilter 추가

---

src/main/java/com/zerobase/hoops/users/repository/redis/AuthRepository.java
src/main/java/com/zerobase/hoops/users/repository/redis/EmailRepository.java
src/main/java/com/zerobase/hoops/users/service/AuthService.java
src/main/java/com/zerobase/hoops/users/service/UserService.java

**AS-IS**
- redis repository, user repository 같은 경로에 위치
**TO-BE**
- 경로 분리

chore : redis 파일 이동

---

src/main/java/com/zerobase/hoops/users/oauth2/service/OAuth2Service.java
src/main/java/com/zerobase/hoops/users/repository/UserRepository.java
src/main/java/com/zerobase/hoops/users/service/UserService.java
src/test/java/com/zerobase/hoops/reports/controller/ReportControllerTest.java

**AS-IS**
- 중복검사 조건 해당 아이디, 이메일, 닉네임으로만 조회해서 있는 경우 false 반환
**TO-BE**
- 탈퇴 회원이 사용했던 아이디, 이메일, 닉네임 사용 가능
- DeletedDateTime Not Null 조건 추가

refactor : 중복 검사 로직 수정

---

src/main/java/com/zerobase/hoops/alarm/repository/EmitterRepository.java
src/main/java/com/zerobase/hoops/alarm/service/NotificationService.java
src/main/java/com/zerobase/hoops/chat/domain/repository/MessageRepository.java
src/main/java/com/zerobase/hoops/users/service/AuthService.java
src/test/java/com/zerobase/hoops/friends/service/FriendServiceTest.java
src/test/java/com/zerobase/hoops/gameCreator/service/ParticipantGameServiceTest.java

**TO-BE**
- 메서드 명 변경
- MessageRepository에 @Repository 어노테이션 추가
- 로그아웃 시 sse연결해제 메서드와 현재까지 받은 알림 삭제하는 메서드 추가

알림서비스 리팩토링

---

src/main/java/com/zerobase/hoops/users/service/UserService.java
src/test/java/com/zerobase/hoops/users/service/UserServiceTest.java

**AS-IS**
- 이메일, 닉네임 중복 확인 try-catch 문 사용
**TO-BE**
- 이메일, 닉네임 중복 확인 try-catch 문 삭제
- 회원 가입 서비스 테스트 코드 작성

test : 회원 가입 서비스 테스트 코드 작성

---

src/main/java/com/zerobase/hoops/friends/repository/FriendRepository.java
src/main/java/com/zerobase/hoops/friends/repository/impl/FriendCustomRepositoryImpl.java
src/main/java/com/zerobase/hoops/friends/service/FriendService.java
src/test/java/com/zerobase/hoops/friends/service/FriendServiceTest.java

**TO-BE**
친구 검색 querydsl 수정
- [V] 테스트 코드
- [V] API 테스트

reactor : 친구 검색 querydsl 수정

---

src/main/java/com/zerobase/hoops/friends/repository/impl/FriendCustomRepositoryImpl.java

**AS-IS**
reactor : 친구 검색 관리자 검색 가능
**TO-BE**
reactor : 친구 검색 관리자 검색 불가능 로직 추가
- [V] 테스트 코드
- [V] API 테스트

reactor : 친구 검색 관리자 검색 불가능 로직 추가

---

src/main/java/com/zerobase/hoops/friends/repository/impl/FriendCustomRepositoryImpl.java

**AS-IS**
reactor : 친구 검색 관리자 검색 불가능 로직 하드코딩
**TO-BE**
reactor : 친구 검색 관리자 검색 불가능 로직 DB 조회 추가
- [V] 테스트 코드
- [V] API 테스트

reactor : 친구 검색 관리자 검색 불가능 로직 DB 조회 추가

---

src/main/java/com/zerobase/hoops/exception/CustomExceptionHandler.java

**AS-IS**
- CustomExceptionHandler 에서 예외 발생 시 ErrorResponse 반환
**TO-BE**
- 예외 발생시 발생한 에러 코드의 상태 코드를 반환하도록 수정

refactor : 예외 발생 핸들러 수정

---

src/main/java/com/zerobase/hoops/gameCreator/repository/ParticipantGameRepository.java
src/main/java/com/zerobase/hoops/invite/service/InviteService.java
src/test/java/com/zerobase/hoops/invite/service/InviteServiceTest.java

**TO-BE**
- 경기 초대 요청
- 수신자가 해당 경기에 참가 하거나 요청한 경우 막음
- 테스트 코드 수정
- [V] 테스트 코드
- [V] API 테스트

경기 초대 요청 테스트 코드 수정

---

src/test/java/com/zerobase/hoops/users/service/UserServiceTest.java

**AS-IS**
**TO-BE**
- 이메일 인증 실패 케이스 테스트 코드 작성

test : confirmEmail 실패 케이스 테스트 코드 추가

---

src/main/java/com/zerobase/hoops/security/TokenProvider.java

**AS-IS**
**TO-BE**
- 토큰 갱신 시 들어오는 토큰 만료 여부 확인 추가

fix : 토큰 갱신 로직 수정

---

src/main/java/com/zerobase/hoops/config/WebSecurityConfig.java
src/main/java/com/zerobase/hoops/security/JwtAuthenticationFilter.java
src/main/java/com/zerobase/hoops/users/controller/AuthController.java

**AS-IS**
- 403 에러 발생 시 반환 내용 없음
**TO-BE**
- 403 에러 json 형식으로 에러 코드 반환

refactor : 403 에러 핸들링

---

src/main/java/com/zerobase/hoops/chat/controller/StompChatController.java
src/main/java/com/zerobase/hoops/chat/service/ChatService.java
src/main/java/com/zerobase/hoops/config/StompWebSocketConfig.java
src/main/java/com/zerobase/hoops/config/WebSecurityConfig.java
src/main/java/com/zerobase/hoops/exception/ErrorCode.java
src/main/java/com/zerobase/hoops/security/JwtAuthenticationFilter.java

**AS-IS**
- 웹소켓 연결을 위한 엔드포인트로 접근 시 403 에러 발생
- 로그인이 필요하게 security 설정되어 있었음
**TO-BE**
- 웹소켓 엔드포인트 인증과정 없이 통과하도록 수정
- 불필요한 어노테이션 삭제

[fix] 웹소켓 엔드포인트로 접근 시 403 에러 발생 해결

---

src/test/java/com/zerobase/hoops/users/service/AuthServiceTest.java

**AS-IS**
**TO-BE**
- AuthService 테스트 코드 작성

Test/hyunjae kwon#99

---

src/main/java/com/zerobase/hoops/friends/repository/impl/FriendCustomRepositoryImpl.java

**TO-BE**
refactor : 친구 리스트 조회 querydsl 수정
- 삭제된 유저는 보이지 않게 query 수정
- [V] API 테스트

refactor : 친구 리스트 조회 querydsl 수정

---

src/main/java/com/zerobase/hoops/chatYohan/config/ConnectionConfig.java
src/main/java/com/zerobase/hoops/config/WebSecurityConfig.java

**AS-IS**
허용 포트 번호 5000
**TO-BE**
허용 포트 번호 5001 로 변경

chore : port 번호 허용 5000 -> 5001

---

src/main/java/com/zerobase/hoops/users/oauth2/service/OAuth2Service.java

**AS-IS**
- 카카오 로그인 시 선택 항목 전체 동의 필수
**TO-BE**
- 카카오 로그인 시 선택 항목 선택에 따른 회원 가입

fix : 카카오 로그인 동의 항목 미선택 상황 코드 추가

---

src/main/java/com/zerobase/hoops/invite/dto/InviteDto.java

refeactor : response mannerPoint로 명시
**TO-BE**
- [V] 테스트 코드
- [V] API 테스트

refeactor : response mannerPoint로 명시

---

src/main/java/com/zerobase/hoops/reports/dto/ReportListResponseDto.java
src/test/java/com/zerobase/hoops/reports/controller/ReportControllerTest.java

**TO-BE**
refeactor : 신고 리스트 response 값 변경
- [V] 테스트 코드
- [V] API 테스트

refeactor : 신고 리스트 response 값 변경

---

src/main/java/com/zerobase/hoops/reports/controller/ReportController.java
src/main/java/com/zerobase/hoops/reports/service/ReportService.java
src/test/java/com/zerobase/hoops/reports/controller/ReportControllerTest.java
src/test/java/com/zerobase/hoops/reports/service/ReportServiceTest.java

변경 및 테스트 코드 수정
**AS-IS**
신고 유저 조회 하기 Response List
**TO-BE**
신고 유저 조회 하기 Response List -> Page
- [V] 테스트 코드
- [V] API 테스트

refeactor : 신고 유저 조회 하기 Response List -> Page

---

src/main/java/com/zerobase/hoops/friends/service/FriendService.java

친구 삭제 조건문 삭제:

---

src/main/java/com/zerobase/hoops/friends/repository/impl/FriendCustomRepositoryImpl.java
src/main/java/com/zerobase/hoops/friends/service/FriendService.java

**TO-BE**
친구 검색 queryDSL 수정
- [V] 테스트 코드
- [V] API 테스트

refactor : 친구 검색 queryDSL 수정

---

src/main/java/com/zerobase/hoops/entity/ChatRoomEntity.java
src/main/java/com/zerobase/hoops/entity/MessageEntity.java
src/main/java/com/zerobase/hoops/gameUsers/service/GameUserService.java

**AS-IS**
- sessionId 디폴트 값 설정 부분 누락
- 지난경기를 통한 매너점수 평가시 본인도 평가할 수 있음
**TO-BE**
- sessionId 누락 부분 수정
- 본인을 제외한 나머지 플레이어들만 평가할 수 있도록 수정
- [o] API 테스트

[FIX] : sessionId 누락 부분 수정 + 매너점수 평가 수정

---

src/main/java/com/zerobase/hoops/entity/ChatRoomEntity.java
src/main/java/com/zerobase/hoops/entity/MessageEntity.java
src/main/java/com/zerobase/hoops/gameUsers/service/GameUserService.java
src/main/java/com/zerobase/hoops/security/TokenProvider.java

[FIX] : 블랙리스트 부분 토큰 수정

---

src/main/java/com/zerobase/hoops/alarm/service/NotificationService.java
src/main/java/com/zerobase/hoops/chat/service/ChatService.java
src/main/java/com/zerobase/hoops/config/WebSocketConnectionConfig.java
src/main/java/com/zerobase/hoops/entity/UserEntity.java
src/main/java/com/zerobase/hoops/friends/dto/FriendDto.java
src/main/java/com/zerobase/hoops/friends/service/FriendService.java
src/main/java/com/zerobase/hoops/gameCreator/dto/GameDto.java
src/main/java/com/zerobase/hoops/gameCreator/dto/ParticipantDto.java
src/main/java/com/zerobase/hoops/gameCreator/service/GameService.java
src/main/java/com/zerobase/hoops/gameCreator/service/ParticipantGameService.java
src/main/java/com/zerobase/hoops/gameUsers/dto/GameSearchResponse.java
src/main/java/com/zerobase/hoops/gameUsers/dto/MannerPointListResponse.java
src/main/java/com/zerobase/hoops/gameUsers/dto/UserJoinsGameDto.java
src/main/java/com/zerobase/hoops/gameUsers/service/GameUserService.java
src/main/java/com/zerobase/hoops/invite/dto/InviteDto.java
src/main/java/com/zerobase/hoops/invite/service/InviteService.java
src/main/java/com/zerobase/hoops/manager/repository/BlackListUserRepository.java
src/main/java/com/zerobase/hoops/manager/service/ManagerService.java
src/main/java/com/zerobase/hoops/reports/dto/ReportListResponseDto.java
src/main/java/com/zerobase/hoops/reports/service/ReportService.java
src/main/java/com/zerobase/hoops/users/dto/KakaoDto.java
src/main/java/com/zerobase/hoops/users/dto/SignUpDto.java
src/main/java/com/zerobase/hoops/users/dto/UserDto.java
src/main/java/com/zerobase/hoops/users/service/AuthService.java

테스트코드 그에 맞게 쪽 수정해야함
**AS-IS**
- UserEntity의 pk 값 -> userId
- 로그인 컬럼 값 -> id
**TO-BE**
- UserEntity의 pk 값 -> id
- 로그인 컬럼 값 -> loginId
머지 후 각자 맡은 엔티티의 pk 값은 id 로 통일하면 됩니다.
기존의 entitiy + id 의 pk 값을 id로 통일 후 각자 작성한 테스트코드 수정해주세요
**BEFORE**
- pk 값 -> entityId 
**AFTER**
- pk 값 -> id

[리펙토링] UserEntity userId pk 컬럼 -> id 로 변경 / id -> loginId로 변경

---

src/main/java/com/zerobase/hoops/alarm/controller/NotificationController.java
src/main/java/com/zerobase/hoops/alarm/domain/NotificationDto.java
src/main/java/com/zerobase/hoops/alarm/service/NotificationService.java

**AS-IS**
- 메서드에 대한 설명을 주석으로 작성함
**TO-BE**
- 메서드명을 통해 해당 메서드가 동작하는 것을 알 수 있으므로 해당 주석 삭제

[refactor] 불필요한 주석 삭제

---

src/main/java/com/zerobase/hoops/security/TokenProvider.java
src/main/java/com/zerobase/hoops/users/controller/AuthController.java
src/main/java/com/zerobase/hoops/users/controller/UserController.java
src/main/java/com/zerobase/hoops/users/dto/EditDto.java
src/main/java/com/zerobase/hoops/users/dto/KakaoDto.java
src/main/java/com/zerobase/hoops/users/dto/LogInDto.java
src/main/java/com/zerobase/hoops/users/dto/SignUpDto.java
src/main/java/com/zerobase/hoops/users/dto/TokenDto.java
src/main/java/com/zerobase/hoops/users/dto/UserDto.java
src/main/java/com/zerobase/hoops/users/oauth2/service/OAuth2Service.java
src/main/java/com/zerobase/hoops/users/provider/EmailProvider.java
src/main/java/com/zerobase/hoops/users/repository/UserRepository.java
src/main/java/com/zerobase/hoops/users/repository/redis/AuthRepository.java
src/main/java/com/zerobase/hoops/users/service/AuthService.java
src/main/java/com/zerobase/hoops/users/service/UserService.java
src/test/java/com/zerobase/hoops/users/service/AuthServiceTest.java
src/test/java/com/zerobase/hoops/users/service/UserServiceTest.java

**AS-IS**
- User 테이블 PK 값 : userId / 로그인 id 값 : id
**TO-BE**
- User 테이블 PK 값 : id / 로그인 id 값 : loginId
- 이에 따른 DTO, Service, Test 코드 수정

refactor : user 테이블 컬럼명 수정에 따른 테스트 코드, 변수 명 및 서비스 명 수정

---

src/main/generated/com/zerobase/hoops/entity/QGameEntity.java
src/main/java/com/zerobase/hoops/entity/GameEntity.java
src/main/java/com/zerobase/hoops/gameCreator/dto/GameDto.java
src/main/java/com/zerobase/hoops/gameCreator/repository/GameRepository.java
src/main/java/com/zerobase/hoops/gameCreator/service/GameService.java
src/main/java/com/zerobase/hoops/gameCreator/service/ParticipantGameService.java
src/main/java/com/zerobase/hoops/gameUsers/dto/GameSearchResponse.java
src/main/java/com/zerobase/hoops/invite/service/InviteService.java
src/main/java/com/zerobase/hoops/users/service/AuthService.java
src/test/java/com/zerobase/hoops/gameCreator/service/GameServiceTest.java
src/test/java/com/zerobase/hoops/gameCreator/service/ParticipantGameServiceTest.java
src/test/java/com/zerobase/hoops/gameUsers/controller/GameUserControllerTest.java
src/test/java/com/zerobase/hoops/gameUsers/service/GameUserServiceTest.java
src/test/java/com/zerobase/hoops/invite/service/InviteServiceTest.java
src/test/java/com/zerobase/hoops/users/service/AuthServiceTest.java

**AS-IS**
GameEntity UserEntity userEntity;
**TO-BE**
GameEntity UserEntity user; 로 변경
해당된 repository 변경
- [V] 테스트 코드
- [V] API 테스트

gameEntity 컬럼명 변경 및 repository 변경

---

src/main/generated/com/zerobase/hoops/entity/QParticipantGameEntity.java
src/main/java/com/zerobase/hoops/config/WebSocketConnectionConfig.java
src/main/java/com/zerobase/hoops/entity/ParticipantGameEntity.java
src/main/java/com/zerobase/hoops/friends/repository/impl/FriendCustomRepositoryImpl.java
src/main/java/com/zerobase/hoops/gameCreator/dto/GameDto.java
src/main/java/com/zerobase/hoops/gameCreator/dto/ParticipantDto.java
src/main/java/com/zerobase/hoops/gameCreator/repository/ParticipantGameRepository.java
src/main/java/com/zerobase/hoops/gameCreator/service/GameService.java
src/main/java/com/zerobase/hoops/gameCreator/service/ParticipantGameService.java
src/main/java/com/zerobase/hoops/gameUsers/dto/MannerPointListResponse.java
src/main/java/com/zerobase/hoops/gameUsers/dto/ParticipateGameDto.java
src/main/java/com/zerobase/hoops/gameUsers/repository/GameCheckOutRepository.java
src/main/java/com/zerobase/hoops/gameUsers/service/GameUserService.java
src/main/java/com/zerobase/hoops/invite/service/InviteService.java
src/main/java/com/zerobase/hoops/users/service/AuthService.java
src/test/java/com/zerobase/hoops/gameCreator/service/GameServiceTest.java
src/test/java/com/zerobase/hoops/gameCreator/service/ParticipantGameServiceTest.java
src/test/java/com/zerobase/hoops/gameUsers/service/GameUserServiceTest.java
src/test/java/com/zerobase/hoops/invite/service/InviteServiceTest.java
src/test/java/com/zerobase/hoops/users/service/AuthServiceTest.java

AS-IS
- ParticipantGameEntity
- private GameEntity gameEntity;
- private UserEntity userEntity;
TO-BE
- ParticipantGameEntity
- private GameEntity game; 로 변경
- private UserEntity user; 로 변경
- [V] 테스트 코드
- [V] API 테스트

refactor : ParticipantGameEntity 컬럼값 변경 및 repository 수정

---

src/main/generated/com/zerobase/hoops/entity/QInviteEntity.java
src/main/java/com/zerobase/hoops/entity/InviteEntity.java
src/main/java/com/zerobase/hoops/entity/ParticipantGameEntity.java
src/main/java/com/zerobase/hoops/friends/repository/impl/FriendCustomRepositoryImpl.java
src/main/java/com/zerobase/hoops/gameCreator/service/GameService.java
src/main/java/com/zerobase/hoops/invite/dto/InviteDto.java
src/main/java/com/zerobase/hoops/invite/repository/InviteRepository.java
src/main/java/com/zerobase/hoops/invite/service/InviteService.java
src/main/java/com/zerobase/hoops/users/service/AuthService.java
src/test/java/com/zerobase/hoops/gameCreator/service/GameServiceTest.java
src/test/java/com/zerobase/hoops/invite/service/InviteServiceTest.java
src/test/java/com/zerobase/hoops/users/service/AuthServiceTest.java

**AS-IS**
- InviteEntity
- private UserEntity senderUserEntity;
- private UserEntity receiverUserEntity;
- private GameEntity gameEntity;
**TO-BE**
- InviteEntity
- private UserEntity senderUser;
- private UserEntity receiverUser;
- private GameEntity game;
- 변경
- [V] 테스트 코드
- [V] API 테스트

refactor : InviteEntity 컬럼값 변경 및 repository 수정

---

src/main/java/com/zerobase/hoops/gameCreator/dto/GameDto.java
src/test/java/com/zerobase/hoops/gameCreator/service/GameServiceTest.java

**AS-IS**
- GameService
- any(), anyLong()
**TO-BE**
- GameService
- eq 로 변경
- [V] 테스트 코드
- [V] API 테스트

test : GameServiceTest.java any 값 삭제 및 올바른 값으로 수정

---

src/main/java/com/zerobase/hoops/gameUsers/controller/GameUserController.java
src/main/java/com/zerobase/hoops/gameUsers/service/GameUserService.java

디폴트 페이지 : 0
디폴트 사이즈 : 5
**AS-IS**
나의 경기 조회 / 지난 경기 조회 / 모든 경기 조회의 경우 -> page의 디폴트 값이 1로 시작
**TO-BE**
page의 디폴트 값 0으로 통일 
- [O] API 테스트

[리펙토링] 페이징처리 1부터시작 -> 0부터 시작으로 통일

---

src/main/java/com/zerobase/hoops/friends/controller/FriendController.java

**AS-IS**
- 친구 리스트 조회
- @PageableDefault(size = 10, page = 0, sort = "FriendUserEntityNickName"
**TO-BE**
- 친구 리스트 조회
- @PageableDefault(size = 10, page = 0, sort = "FriendUserNickName" 로 변경
- [V] API 테스트

refactor : 친구 리스트 조회 Pageable sort 수정

---

src/main/java/com/zerobase/hoops/config/WebSecurityConfig.java
src/main/java/com/zerobase/hoops/friends/controller/FriendController.java
src/main/java/com/zerobase/hoops/gameCreator/controller/GameController.java
src/main/java/com/zerobase/hoops/gameCreator/controller/ParticipantGameController.java
src/main/java/com/zerobase/hoops/invite/controller/InviteController.java
src/test/java/com/zerobase/hoops/gameCreator/service/ParticipantGameServiceTest.java

**AS-IS**
.requestMatchers().hasRole("USER")
**TO-BE**
@PreAuthorize("hasRole('USER')") 로 변경
- [V] API 테스트

refactor : WebSecurityConfig -> @PreAuthorize 로 변경

---

src/main/java/com/zerobase/hoops/config/WebSecurityConfig.java
src/main/java/com/zerobase/hoops/users/controller/AuthController.java

**AS-IS**
- WebSecurityConfig 에서 인가 요청 url 지정
**TO-BE**
- AuthController 내 인가 필요 url @PreAuthorize 추가

refactor : Security Config 인가 요청 방식 수정

---

src/main/java/com/zerobase/hoops/entity/ChatRoomEntity.java
src/main/java/com/zerobase/hoops/entity/GameEntity.java
src/main/java/com/zerobase/hoops/entity/ParticipantGameEntity.java
src/main/java/com/zerobase/hoops/gameCreator/repository/ParticipantGameRepository.java
src/main/java/com/zerobase/hoops/gameCreator/service/GameService.java
src/main/java/com/zerobase/hoops/gameCreator/service/ParticipantGameService.java
src/test/java/com/zerobase/hoops/gameCreator/service/GameServiceTest.java
src/test/java/com/zerobase/hoops/gameCreator/service/ParticipantGameServiceTest.java
src/test/java/com/zerobase/hoops/invite/service/InviteServiceTest.java

**AS-IS**
- 경기, 경기 참가
- save(any())
**TO-BE**
- 경기, 경기 참가
- save(any()) 삭제 및 맞는 Entity로 수정
- 경기 참가 희망자 리스트 조회 테스트 코드 구현
- 해당 Entity에 equals, hashCode 구현
- [V] 테스트 코드

테스트 코드 any() 삭제

---

src/main/java/com/zerobase/hoops/config/TimeConfig.java
src/main/java/com/zerobase/hoops/entity/FriendEntity.java
src/main/java/com/zerobase/hoops/friends/controller/FriendController.java
src/main/java/com/zerobase/hoops/friends/dto/FriendDto.java
src/main/java/com/zerobase/hoops/friends/repository/FriendCustomRepository.java
src/main/java/com/zerobase/hoops/friends/repository/impl/FriendCustomRepositoryImpl.java
src/main/java/com/zerobase/hoops/friends/service/FriendService.java
src/test/java/com/zerobase/hoops/friends/service/FriendServiceTest.java

**AS-IS**
- FriendServiceTest
- anyLong(), any() 로 구현
**TO-BE**
- FriendServiceTest
- anyLong(), any() 삭제
- 실패케이스 작성
- LocalDateTime.now 테스트 부분 구현
- Clock Bean 등록
- [V] 테스트 코드
- [V] API 테스트

FriendServiceTest any()삭제 및 실패케이스 작성

---

src/main/resources/logback-spring.xml

**TO-BE**
logback-spring.xml 작성
- [V] API 테스트

refactor : logback-spring.xml 작성

---

src/main/java/com/zerobase/hoops/entity/ChatRoomEntity.java
src/main/java/com/zerobase/hoops/entity/GameEntity.java
src/main/java/com/zerobase/hoops/entity/InviteEntity.java
src/main/java/com/zerobase/hoops/entity/ParticipantGameEntity.java
src/main/java/com/zerobase/hoops/gameCreator/controller/GameController.java
src/main/java/com/zerobase/hoops/gameCreator/dto/GameDto.java
src/main/java/com/zerobase/hoops/gameCreator/service/GameService.java
src/test/java/com/zerobase/hoops/gameCreator/service/GameServiceTest.java

**TO-BE**
- 경기
- service 메서드 최적화
- reponse 안쓰는 값 정리
- 누락 테스트 코드 추가
- [V] 테스트 코드
- [V] API 테스트

refactor : 경기 service 메서드 최적화 및 response 안쓰는 값 정리

---

src/main/java/com/zerobase/hoops/entity/ParticipantGameEntity.java
src/main/java/com/zerobase/hoops/gameCreator/controller/ParticipantGameController.java
src/main/java/com/zerobase/hoops/gameCreator/dto/ParticipantDto.java
src/main/java/com/zerobase/hoops/gameCreator/repository/ParticipantGameRepository.java
src/main/java/com/zerobase/hoops/gameCreator/service/ParticipantGameService.java
src/test/java/com/zerobase/hoops/gameCreator/service/ParticipantGameServiceTest.java

**TO-BE**
- 경기 참가
- request, response 값 정리
- 리스트 페이징 추가
- 누락된 테스트 코드 추가
- 서비스 코드 로직 정리
- [V] 테스트 코드
- [V] API 테스트

경기 참가 response 정리 및 로직 정리

---

src/test/java/com/zerobase/hoops/invite/service/InviteServiceTest.java

**AS-IS**
- acceptedDateTime(nowDateTime)
**TO-BE**
- acceptedDateTime(nowDateTime) 삭제
- [V] 테스트 코드

친구 초대 테스트코드 에러 수정

---

src/main/java/com/zerobase/hoops/invite/controller/InviteController.java
src/main/java/com/zerobase/hoops/invite/dto/InviteDto.java
src/main/java/com/zerobase/hoops/invite/repository/InviteRepository.java
src/main/java/com/zerobase/hoops/invite/service/InviteService.java
src/test/java/com/zerobase/hoops/invite/service/InviteServiceTest.java

**TO-BE**
- 경기 초대
- request, response 정리
- service 로직 정리
- 리스트 페이징 처리
- 테스트 코드 정리
- [V] 테스트 코드
- [V] API 테스트

초대 service 코드 정리

---

.gitignore
src/main/java/com/zerobase/hoops/gameUsers/service/GameUserService.java
src/main/java/com/zerobase/hoops/manager/service/ManagerService.java
src/main/java/com/zerobase/hoops/reports/service/ReportService.java

**AS-IS**
**TO-BE**
- GameUserService / ManagerService / ReportService 로그 기록 추가
- gitignore -> logs 폴더 제외
- [o] 테스트 코드
- [o] API 테스트

[리펙토링] log 추가

---

src/main/java/com/zerobase/hoops/config/SwaggerConfig.java

**TO-BE**
- swagger-config 수정
- [V] API 테스트

refactor : SwaggerConfig 수정

---

src/main/java/com/zerobase/hoops/config/SwaggerConfig.java

**TO-BE**
- swaggerConfig
- 커스텀 타입 이름 구현
- [V] API 테스트

[refactor] springDocs swagger inner class 인식 불가 문제 수정

---

src/main/java/com/zerobase/hoops/users/controller/AuthController.java
src/main/java/com/zerobase/hoops/users/controller/UserController.java
src/main/java/com/zerobase/hoops/users/dto/CheckDto.java
src/main/java/com/zerobase/hoops/users/dto/EditDto.java
src/main/java/com/zerobase/hoops/users/dto/FindDto.java
src/main/java/com/zerobase/hoops/users/dto/KakaoDto.java
src/main/java/com/zerobase/hoops/users/dto/LogInDto.java
src/main/java/com/zerobase/hoops/users/dto/SignUpDto.java
src/main/java/com/zerobase/hoops/users/dto/UserDto.java
src/main/java/com/zerobase/hoops/users/oauth2/controller/OAuth2Controller.java

**AS-IS**
- Swagger 설정 최소화
**TO-BE**
- User, Auth, OAuth2 컨트롤러 및 DTO Swagger 설정으로 Example Value, Schema 설명 추가
- CheckDto, FindDto 추가 : API의 response 형식 통일

refactor : USER, AUTH swagger 설정 추가

---

.dockerignore
.github/workflowers/hoops-backend-build-and-push.yml
.github/workflows/hoops-backend-build-and-push.yml
.gitignore
Dockerfile
docker-compose.yml
src/main/java/com/zerobase/hoops/users/provider/EmailProvider.java
src/main/resources/application.yml
src/main/resources/logback-spring.xml

**AS-IS**
- 로컬 환경에서 개발 진행
- 배포시 수동으로 진행
**TO-BE**
- 도커 컨테이너로 개발환경 분리
- yohan-main 브런치 분리 및 자동 배포
- [O] 테스트 코드
- [O] API 테스트

[기능 추가] 도커 컨테이너 추가 및 CI/CD 설정

---

.github/workflows/hoops-backend-build-and-push.yml
docker-compose.yml

**AS-IS**
- docker-compose 에 버전 1
- ec2 서버에 깃 소스파일을 가져와서 다시 빌드 진행
**TO-BE**
- docker-compose 에 버전 1 삭제 -> 디폴트로 진행
- ec2에는 docker-compose.yml 파일만 두고 나머지 소스파일들은 삭제 -> CI/CD에서 빌드된 이미지파일 -> 도커허브에서 pull 로 땡겨서 진행
- ec2에서 이전에 사용되었던 불필요한 이미지 파일들 삭제

[FIX] CI/CD 명령어 변경 

---

.github/workflows/hoops-backend-build-and-push.yml
src/main/java/com/zerobase/hoops/HoopsApplication.java
src/main/java/com/zerobase/hoops/config/SwaggerConfig.java

**AS-IS**
https 에서 swagger cors 에러
**TO-BE**
application.java 파일에서
@OpenAPIDefinition(servers = {@Server(url = "https://yohanyohan.com")}) 도메인 추가
- [o] 테스트 코드
- [o] API 테스트

[FIX] swagger https 프로토콜 cors 에러 

---

.github/workflows/hoops-backend-build-and-push.yml
src/main/java/com/zerobase/hoops/HoopsApplication.java
src/main/java/com/zerobase/hoops/config/SwaggerConfig.java
src/main/java/com/zerobase/hoops/config/WebSecurityConfig.java
src/main/java/com/zerobase/hoops/gameUsers/controller/GameUserController.java
src/main/java/com/zerobase/hoops/gameUsers/service/GameUserService.java
src/test/java/com/zerobase/hoops/gameUsers/controller/GameUserControllerTest.java
src/test/java/com/zerobase/hoops/gameUsers/service/GameUserServiceTest.java

[FIX] HTTPS swagger 응답 수정

---

.github/workflows/hoops-backend-build-and-push.yml
src/main/java/com/zerobase/hoops/manager/controller/ManagerController.java
src/main/java/com/zerobase/hoops/manager/service/ManagerService.java
src/main/java/com/zerobase/hoops/reports/repository/ReportRepository.java
src/main/java/com/zerobase/hoops/reports/service/ReportService.java
src/test/java/com/zerobase/hoops/manager/service/ManagerServiceTest.java

**AS-IS**
- 한 유저가 여러 명에게 신고를 당했을 경우 버그 발생
- 신고를 이미 했음에도 계속적으로 신고 가능
**TO-BE**
- 한 유저가 여러 명에게 동시에 신고를 당하더라도 에러 없이 일괄 처리
- 중복 신고 방지
- [O] 테스트 코드
- [O] API 테스트

[FIX] 블랙리스트 및 중복신고 수정
